### PR TITLE
feature: support hex strings as input for IOTileDeviceSlug

### PR DESCRIPTION
**Pull request by JKHeadley**
Since it was a simple fix I added support for hex strings rather than throwing an error.

### CODE REVIEW

**Review by dkarchmer — APPROVED** [review]
Need to change version.py and CHANGELOG.md so we can release new version.

**Comment by JKHeadley** [comment]
@dkarchmer updated version.py and changelog. Please verify that I used the correct version update format. Also, some checks have failed, is that an issue?

**Comment by dkarchmer** [comment]
@JKHeadley yes, format is ok. Not sure why appveyor is failing. It has been a while since we have done updates here. If you can merge, go ahead. as the Travis test is all that matters

**Comment by JKHeadley** [comment]
@dkarchmer merged. Does this automatically get deployed?

**Pull request merged**
